= get-sts-cc-git-credentials.sh


== Description

To be able to clone a CodeCommit repository on an AWS EC2 instance running Linux you need security credentials or else you'll run into the following:

```console
$ git clone https://git-codecommit.us-east-1.amazonaws.com/v1/repos/test-repo
Cloning into 'test-repo'...
Username for 'https://git-codecommit.us-east-1.amazonaws.com': ^C
$
```

This script is a `credential.helper` for `git` that uses temporary security credentials from an AWS IAM role provided by AWS Security Token Service (AWS STS).


== Usage

This script cannot be used stand-alone, it must be executed using the `git` command.


=== Prerequisites:

1. An EC2 instance running Linux (see: `Tested Linux distributions`);
2. Installed `awscli`;
3. Installed `curl`;
4. Installed `git`;
5. A CodeCommit repository (e.g.: `XXX_cc_repo`);
6. An IAM role (e.g.: `XXX_iam_role`) that has `codecommit:*` with the `allow` effect on the CodeCommit repository ARN;
7. An appropriate IAM instance policy attached to the EC2 instance that allows `AssumeRole` of the role from step `6`.


=== Installation steps

For the example below to work you need to install `get-sts-cc-git-credentials.sh` to `/usr/local/bin`:

```sh
cd /tmp
git clone https://github.com/riboseinc/get-sts-cc-git-credentials
sudo install -m 0555 -o root -g root get-sts-cc-git-credentials/get-sts-cc-git-credentials.sh /usr/local/bin
```

=== Run

```sh
git clone \
        -c credential.UseHttpPath=true \
        -c credential.helper='!/usr/local/bin/get-sts-cc-git-credentials.sh XXX_iam_role' \
        --no-progress 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/XXX_cc_repo'
```


=== Example run after installation

```console
$ git clone -c credential.UseHttpPath=true -c credential.helper='!/usr/local/bin/get-sts-cc-git-credentials.sh XXX_iam_role' --no-progress 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/XXX_cc_repo'
Cloning into 'XXX_cc_repo'...
remote: Counting objects: 344, done.
Receiving objects: 100% (344/344), 96.25 KiB | 126.00 KiB/s, done.
Resolving deltas: 100% (101/101), done.
$
```

Optionally you can also specify a different AWS account id (e.g.: `XXX_aws_accountid`) if the IAM role is delegated from another account.

```sh
git clone \
	-c credential.UseHttpPath=true \
	-c credential.helper='!/usr/local/bin/get-sts-cc-git-credentials.sh XXX_iam_role XXX_aws_accountid' \
	--no-progress 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/XXX_cc_repo'
```


== Tested Linux distributions

1. Red Hat Enterprise Linux 7
2. CentOS 7


== Contributions

Feel free to open an issue or to send a pull request.
